# Further Cleaning/Wrangling of COVID-19 dataset

## This script contains:
### 1. Changing daily entries to monthly
### 2. Importing a new dataset with more relevant datset
### 3. Cleaning & Wrangling new dataset
### 4. Combining 2 datasets

## 1. Changing daily entries to monthly

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Create path to dataset
path = r'C:\Users\M de Villiers\Desktop\Data Analytics\Achievement 6\02_Data\Prepared_Data'

In [3]:
# import data
df= pd.read_csv(os.path.join(path, 'covid_vaccinations_clean.csv'), index_col=False)

In [4]:
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines
0,Afghanistan,AFG,2021-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
1,Afghanistan,AFG,2021-02-23,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
2,Afghanistan,AFG,2021-02-24,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
3,Afghanistan,AFG,2021-02-25,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
4,Afghanistan,AFG,2021-02-26,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."

In [5]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines
81971,Zimbabwe,ZWE,2022-03-03,7921113.0,4372925.0,3406482.0,10373.0,8903.0,52.48,28.97,22.57,590.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
81972,Zimbabwe,ZWE,2022-03-04,7930621.0,4374896.0,3408609.0,9508.0,8603.0,52.55,28.99,22.59,570.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
81973,Zimbabwe,ZWE,2022-03-05,7936145.0,4377373.0,3410340.0,5524.0,8458.0,52.58,29.00,22.60,560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
81974,Zimbabwe,ZWE,2022-03-06,7938362.0,4378029.0,3410960.0,2217.0,8017.0,52.60,29.01,22.60,531.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
81975,Zimbabwe,ZWE,2022-03-07,7943325.0,4379875.0,3412556.0,4963.0,7482.0,52.63,29.02,22.61,496.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."

In [6]:
df.shape

(81976, 13)

In [7]:
# Extracting month and year from date to group by month and date for time series
df['month_year'] = pd.to_datetime(df['date']).dt.to_period('M')

In [8]:
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,month_year
0,Afghanistan,AFG,2021-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2021-02
1,Afghanistan,AFG,2021-02-23,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2021-02
2,Afghanistan,AFG,2021-02-24,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2021-02
3,Afghanistan,AFG,2021-02-25,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2021-02
4,Afghanistan,AFG,2021-02-26,0.0,0.0,0.0,0.0,1367.0,0.0,0.0,0.0,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2021-02

In [9]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,month_year
81971,Zimbabwe,ZWE,2022-03-03,7921113.0,4372925.0,3406482.0,10373.0,8903.0,52.48,28.97,22.57,590.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2022-03
81972,Zimbabwe,ZWE,2022-03-04,7930621.0,4374896.0,3408609.0,9508.0,8603.0,52.55,28.99,22.59,570.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2022-03
81973,Zimbabwe,ZWE,2022-03-05,7936145.0,4377373.0,3410340.0,5524.0,8458.0,52.58,29.00,22.60,560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2022-03
81974,Zimbabwe,ZWE,2022-03-06,7938362.0,4378029.0,3410960.0,2217.0,8017.0,52.60,29.01,22.60,531.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2022-03
81975,Zimbabwe,ZWE,2022-03-07,7943325.0,4379875.0,3412556.0,4963.0,7482.0,52.63,29.02,22.61,496.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2022-03

In [10]:
# Export new dataset
df.to_csv(os.path.join(path, 'COVID-19_vaccinations_2.csv'), index=False)

In [11]:
df1 = df.groupby(['country', 'iso_code', 'month_year', 'vaccines'], as_index=False).agg(total_vaccinations = ('total_vaccinations', 'max'), people_vaccinated = ('people_vaccinated', 'max'), people_fully_vaccinated = ('people_fully_vaccinated', 'max'), monthly_vaccinations_raw = ('daily_vaccinations_raw', 'sum'), monthly_vaccinations = ('daily_vaccinations', 'sum'), total_vaccinations_per_hundred = ('total_vaccinations_per_hundred', 'max'), people_vaccinated_per_hundred = ('people_vaccinated_per_hundred', 'max'), people_fully_vaccinated_per_hundred = ('people_fully_vaccinated_per_hundred', 'max'), monthly_vaccinations_per_million = ('daily_vaccinations_per_million', 'sum'))

In [12]:
df1.head()

,country,iso_code,month_year,vaccines,total_vaccinations,people_vaccinated,people_fully_vaccinated,monthly_vaccinations_raw,monthly_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,monthly_vaccinations_per_million
0,Afghanistan,AFG,2021-02,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",8200.0,8200.0,0.0,0.0,8202.0,0.02,0.02,0.00,204.0
1,Afghanistan,AFG,2021-03,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",54000.0,54000.0,0.0,0.0,85894.0,0.14,0.14,0.00,2154.0
2,Afghanistan,AFG,2021-04,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",240000.0,240000.0,0.0,0.0,219606.0,0.60,0.60,0.00,5511.0
3,Afghanistan,AFG,2021-05,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",600152.0,480226.0,119926.0,2859.0,285838.0,1.51,1.21,0.30,7171.0
4,Afghanistan,AFG,2021-06,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",886854.0,699200.0,187654.0,4015.0,242899.0,2.23,1.76,0.47,6097.0

In [13]:
df1.tail()

,country,iso_code,month_year,vaccines,total_vaccinations,people_vaccinated,people_fully_vaccinated,monthly_vaccinations_raw,monthly_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,monthly_vaccinations_per_million
2961,Zimbabwe,ZWE,2021-11,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",6611942.0,3795401.0,2816541.0,618042.0,679619.0,43.81,25.15,18.66,45028.0
2962,Zimbabwe,ZWE,2021-12,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7264791.0,4124378.0,3135168.0,626997.0,679454.0,48.14,27.33,20.77,45019.0
2963,Zimbabwe,ZWE,2022-01,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7632514.0,4270759.0,3299624.0,367723.0,375550.0,50.57,28.30,21.86,24882.0
2964,Zimbabwe,ZWE,2022-02,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7890951.0,4362150.0,3396655.0,258437.0,258018.0,52.29,28.90,22.51,17096.0
2965,Zimbabwe,ZWE,2022-03,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7943325.0,4379875.0,3412556.0,52374.0,59815.0,52.63,29.02,22.61,3963.0

In [14]:
df1.shape

(2966, 13)

In [15]:
# Export monthly dataset
df1.to_csv(os.path.join(path, 'monthly_COVID-19_vaccinations.csv'), index=False)

# 2. Importing new Dataset

In [16]:
#create new path
path2 = r'C:\Users\M de Villiers\Desktop\Data Analytics\Achievement 6\02_Data\Original_Data'

In [17]:
df2 = pd.read_csv(os.path.join(path2, 'population_by_country_2020.csv'), index_col=False)

In [18]:
df2.head()

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,Afghanistan,39074280,2.33%,886592.0,60.0,652860.0,-62920.0,4.6,18,25%,0.50%
1,Albania,2877239,-0.11%,-3120.0,105.0,27400.0,-14000.0,1.6,36,63%,0.04%
2,Algeria,43984569,1.85%,797990.0,18.0,2381740.0,-10000.0,3.1,29,73%,0.56%
3,American Samoa,55169,-0.22%,-121.0,276.0,200.0,NaN,N.A.,N.A.,88%,0.00%
4,Andorra,77287,0.16%,123.0,164.0,470.0,NaN,N.A.,N.A.,88%,0.00%

In [19]:
df2.tail()

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
240,Wallis and Futuna,11203,-1.69%,-193.0,80.0,140.0,NaN,N.A.,N.A.,0%,0.00%
241,Western Sahara,599769,2.55%,14876.0,2.0,266000.0,5582.0,2.4,28,87%,0.01%
242,Yemen,29935468,2.28%,664042.0,56.0,527970.0,-30000.0,3.8,20,38%,0.38%
243,Zambia,18468257,2.93%,522925.0,25.0,743390.0,-8000.0,4.7,18,45%,0.24%
244,Zimbabwe,14899771,1.48%,217456.0,38.0,386850.0,-116858.0,3.6,19,38%,0.19%

# 3. Cleaning & Wrangling new dataset

In [20]:
# dropping columns: Instead of dropping columns, I will just create a new dataset with the columns I need
# I want to drop more columns than I actually need so I think this way is easier
df3 = df2[['Country (or dependency)', 'Population (2020)']]

In [21]:
df3.head(10)

  Country (or dependency)  Population (2020)
0             Afghanistan           39074280
1                 Albania            2877239
2                 Algeria           43984569
3          American Samoa              55169
4                 Andorra              77287
5                  Angola           33032075
6                Anguilla              15026
7     Antigua and Barbuda              98069
8               Argentina           45267449
9                 Armenia            2964219

In [22]:
df3.rename(columns = {'Country (or dependency)' : 'country'}, inplace=True)

C:\Users\M de Villiers\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [23]:
df3.head()

          country  Population (2020)
0     Afghanistan           39074280
1         Albania            2877239
2         Algeria           43984569
3  American Samoa              55169
4         Andorra              77287

In [24]:
df3.tail(15)

                  country  Population (2020)
230               Ukraine           43686577
231  United Arab Emirates            9910892
232        United Kingdom           67081000
233         United States          331341050
234               Uruguay            3475842
235            Uzbekistan           33551824
236               Vanuatu             308337
237             Venezuela           28421581
238               Vietnam           97490013
239                 Wales            3170000
240     Wallis and Futuna              11203
241        Western Sahara             599769
242                 Yemen           29935468
243                Zambia           18468257
244              Zimbabwe           14899771

# 4. Combining datasets

In [25]:
df_merged = df3.merge(df1, on = 'country', how = 'outer', sort=False)

In [26]:
df_merged.head(20)

,country,Population (2020),iso_code,month_year,vaccines,total_vaccinations,people_vaccinated,people_fully_vaccinated,monthly_vaccinations_raw,monthly_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,monthly_vaccinations_per_million
0,Afghanistan,39074280,AFG,2021-02,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",8200.0,8200.0,0.0,0.0,8202.0,0.02,0.02,0.00,204.0
1,Afghanistan,39074280,AFG,2021-03,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",54000.0,54000.0,0.0,0.0,85894.0,0.14,0.14,0.00,2154.0
2,Afghanistan,39074280,AFG,2021-04,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",240000.0,240000.0,0.0,0.0,219606.0,0.60,0.60,0.00,5511.0
3,Afghanistan,39074280,AFG,2021-05,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",600152.0,480226.0,119926.0,2859.0,285838.0,1.51,1.21,0.30,7171.0
4,Afghanistan,39074280,AFG,2021-06,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",886854.0,699200.0,187654.0,4015.0,242899.0,2.23,1.76,0.47,6097.0
5,Afghanistan,39074280,AFG,2021-07,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",1171064.0,742934.0,219159.0,0.0,337196.0,2.94,1.87,0.55,8466.0
6,Afghanistan,39074280,AFG,2021-08,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",1979652.0,773002.0,430744.0,0.0,591825.0,4.97,1.94,1.08,14854.0
7,Afghanistan,39074280,AFG,2021-09,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",2369625.0,828601.0,0.0,0.0,563255.0,5.95,2.08,0.00,14132.0
8,Afghanistan,39074280,AFG,2021-10,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",0.0,0.0,0.0,0.0,1064777.0,0.00,0.00,0.00,26738.0
9,Afghanistan,39074280,AFG,2021-11,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4018197.0,3530173.0,3188609.0,0.0,821215.0,10.09,8.86,8.00,20618.0
10,Afghanistan,39074280,AFG,2021-12,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4674518.0,4142857.0,3753224.0,0.0,476498.0,11.73,10.40,9.42,11958.0
11,Afghanistan,39074280,AFG,2022-01,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",5125146.0,4554648.0,3892831.0,6868.0,399710.0,12.87,11.43,9.77,10038.0
12,Afghanistan,39074280,AFG,2022-02,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",5535254.0,4907058.0,4231984.0,0.0,406044.0,13.90,12.32,10.62,10195.0
13,Afghanistan,39074280,AFG,2022-03,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",5597130.0,4952744.0,4281934.0,0.0,71731.0,14.05,12.43,10.75,1800.0
14,Albania,2877239,ALB,2021-01,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",549.0,549.0,0.0,421.0,741.0,0.02,0.02,0.00,257.0
15,Albania,2877239,ALB,2021-02,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",10135.0,6073.0,655.0,2476.0,9504.0,0.35,0.21,0.02,3305.0
16,Albania,2877239,ALB,2021-03,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",138846.0,0.0,0.0,49296.0,78590.0,4.83,0.00,0.00,27354.0
17,Albania,2877239,ALB,2021-04,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",476903.0,0.0,0.0,295509.0,339023.0,16.60,0.00,0.00,118004.0
18,Albania,2877239,ALB,2021-05,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",776461.0,486128.0,290333.0,204550.0,333048.0,27.03,16.92,10.11,115927.0
19,Albania,2877239,ALB,2021-06,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",968034.0,564530.0,403504.0,134454.0,180622.0,33.69,19.65,14.05,62871.0

In [27]:
df_merged.tail(15)

,country,Population (2020),iso_code,month_year,vaccines,total_vaccinations,people_vaccinated,people_fully_vaccinated,monthly_vaccinations_raw,monthly_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,monthly_vaccinations_per_million
2973,Zambia,18468257,ZMB,2022-03,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm...",3027612.0,2510296.0,1983053.0,25849.0,125122.0,16.00,13.27,10.48,6613.0
2974,Zimbabwe,14899771,ZWE,2021-02,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",19100.0,19100.0,0.0,15059.0,11813.0,0.13,0.13,0.00,782.0
2975,Zimbabwe,14899771,ZWE,2021-03,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",92426.0,77541.0,14885.0,73326.0,67198.0,0.61,0.51,0.10,4452.0
2976,Zimbabwe,14899771,ZWE,2021-04,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",500320.0,414733.0,85587.0,350105.0,361818.0,3.32,2.75,0.57,23972.0
2977,Zimbabwe,14899771,ZWE,2021-05,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",1020056.0,675676.0,344380.0,447092.0,536999.0,6.76,4.48,2.28,35582.0
2978,Zimbabwe,14899771,ZWE,2021-06,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",1332416.0,777159.0,555257.0,303887.0,293276.0,8.83,5.15,3.68,19429.0
2979,Zimbabwe,14899771,ZWE,2021-07,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",2433070.0,1653821.0,779249.0,867690.0,1041443.0,16.12,10.96,5.16,69005.0
2980,Zimbabwe,14899771,ZWE,2021-08,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",4219824.0,2582405.0,1637419.0,1574976.0,1800117.0,27.96,17.11,10.85,119276.0
2981,Zimbabwe,14899771,ZWE,2021-09,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",5346026.0,3074191.0,2271835.0,992208.0,1147935.0,35.42,20.37,15.05,76064.0
2982,Zimbabwe,14899771,ZWE,2021-10,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",5911588.0,3316429.0,2595159.0,565562.0,614428.0,39.17,21.97,17.20,40713.0
2983,Zimbabwe,14899771,ZWE,2021-11,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",6611942.0,3795401.0,2816541.0,618042.0,679619.0,43.81,25.15,18.66,45028.0
2984,Zimbabwe,14899771,ZWE,2021-12,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7264791.0,4124378.0,3135168.0,626997.0,679454.0,48.14,27.33,20.77,45019.0
2985,Zimbabwe,14899771,ZWE,2022-01,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7632514.0,4270759.0,3299624.0,367723.0,375550.0,50.57,28.30,21.86,24882.0
2986,Zimbabwe,14899771,ZWE,2022-02,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7890951.0,4362150.0,3396655.0,258437.0,258018.0,52.29,28.90,22.51,17096.0
2987,Zimbabwe,14899771,ZWE,2022-03,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",7943325.0,4379875.0,3412556.0,52374.0,59815.0,52.63,29.02,22.61,3963.0

In [28]:
df_merged.shape

(2988, 14)

In [29]:
df_merged.to_csv(os.path.join(path, 'monthly_COVID-19_vaccinations_3.csv'), index=False)